layout_spectrum: 0.14715178683400154
typography_spectrum: 0.18516520410776138
color:
  saturation: 0.3096650305669755
  brandStrength: 0.29762318218126893
  lightness: 0.18787586595863104
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  rhythmicContrast: 0.2551166682969779
content_rating:
  adult: false
opengraph:
  image: null
  type: null
  appId: ''
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Alberto
  email: aguirreb29@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/49586341-9056-4873-b583-9fe3d15604b7.jpg
name: Grammaton Cleric
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Newest Addition To The Cleric Magnitude
description: The First Original Impression
purpose: []
