layout_spectrum: 0.3604568485170603
typography_spectrum: 0.8644320205785334
color:
  brandColors:
    - '#DDDCC5'
    - '#958976'
    - '#611427'
    - '#1D2326'
    - '#6A6A61'
  brandStrength: 0.7007325817830861
  lightness: 0.2512564721982926
  saturation: 0.25229558162391186
  rhythmicContrast: 0.836520905373618
name: Grammaton Cleric
favicon: null
content_rating:
  adult: false
author:
  name: Alberto
  email: aguirreb29@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/49586341-9056-4873-b583-9fe3d15604b7.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Newest Addition To The Cleric Magnitude
description: The First Original Impression
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: ''
purpose: []
